version: '3.4'

services:
  eshopdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  distributedcache:
    image: redis

  seq:
    image: datalust/seq:latest

volumes:
  postgres_eshopdb:
  pgadmin_data:  